# Generated by Django 4.2.20 on 2025-05-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('house', 'House'), ('townhouse', 'Townhouse'), ('apartment', 'Apartment')], max_length=20)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('sold', models.BooleanField(default=False)),
                ('rooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='property_thumbnails/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='properties/images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery', to='properties.property')),
            ],
        ),
    ]
