# Generated by Django 5.2 on 2025-05-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('mortgage', 'Mortgage')], max_length=20)),
                ('cardholder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.DateField(blank=True, max_length=7, null=True)),
                ('cvc', models.CharField(blank=True, max_length=3, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mortgage_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('purchase_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_offer', to='offers.purchaseoffer')),
            ],
        ),
    ]
