# Generated by Django 4.2.20 on 2025-05-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoffer',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='finalizedoffer',
            name='purchase_offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_offer', to='offers.purchaseoffer'),
        ),
    ]
