# Generated by Django 5.2 on 2025-05-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_finalizedoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedoffer',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
