# Generated by Django 4.2.20 on 2025-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='property_thumbnails/')),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_rooms', models.IntegerField()),
                ('square_meters', models.FloatField()),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
    ]
